FoodDelivery/ViewModels/Food/FoodEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FoodDelivery.ViewModels.Food
{
    public class FoodEditModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Наименование")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Цена")]
        public int Price { get; set; }
        [Required]
        [Display(Name = "Описание")]
        public string Description { get; set; }
        public int EstablishmentId { get; set; }
    }
}

FoodDelivery/ViewModels/Food/FoodViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FoodDelivery.ViewModels.Food
{
    public class FoodViewModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Наименование")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Цена")]
        public int Price { get; set; }
        [Required]
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Required]
        public int EstablishmentId { get; set; }
    }
}

FoodDelivery/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FoodDelivery.DAL;
using FoodDelivery.Domain.Dtos.Food;
using FoodDelivery.Domain.Services;
using FoodDelivery.ViewModels;
using FoodDelivery.ViewModels.Food;
using Microsoft.AspNetCore.Mvc;
using FoodDelivery.ViewModels.FlashMessage;
using Microsoft.AspNetCore.Authorization;

namespace FoodDelivery.Controllers
{
    public class FoodController : ControllerBase
    {
        private readonly IFoodService _foodService;
        private readonly IMapper _mapper;

        public FoodController(IFoodService foodService, IMapper mapper)
        {
            _foodService = foodService;
            _mapper = mapper;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create(int establishmentId)
        {
            var food = new FoodViewModel
            {
                EstablishmentId = establishmentId
            };
            return PartialView("_Create", food);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(FoodViewModel foodViewModel)
        {
            if (ModelState.IsValid)
            {
                var food = _mapper.Map<FoodCreateDto>(foodViewModel);
                var result = await _foodService.CreateAsync(food);
                if (result.IsSuccess)
                {
                    SetFlash(new FlashMessage("Блюдо успешно добавлено", FlashMessageType.Success));
                }
                else
                {
                    SetFlash(new FlashMessage(result.Errors.First(), FlashMessageType.Danger));
                }
            }
            else
                SetFlash(new FlashMessage("Ошибка при заполнении формы", FlashMessageType.Danger));
            return RedirectToAction("Details", "Establishment", new { id = foodViewModel.EstablishmentId });
        }

        public async Task<IActionResult> Index(int id)
        {
            var result = await _foodService.GetByEstablishmentIdAsync(id);
            var food = new List<FoodViewModel>();
            if (result.IsSuccess)
                food = _mapper.Map<List<FoodViewModel>>(result.Entity);           
            else              
                AddErrors(result);
            return PartialView("_Index", food);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var result = _foodService.GetById(id);
            FoodEditModel foodEditModel;
            if(result.IsSuccess)
            {
                foodEditModel = _mapper.Map<FoodEditModel>(result.Entity);
            }
            else
            {
                AddErrors(result);
                foodEditModel = new FoodEditModel();
            }
            return PartialView("_Edit",foodEditModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(FoodEditModel foodEditModel)
        {
            if (ModelState.IsValid)
            {
                var foodDto = _mapper.Map<FoodEditDto>(foodEditModel);
                var result = await _foodService.EditAsync(foodDto);
                if (result.IsSuccess)
                {
                    SetFlash(new FlashMessage("Блюдо успешно изменено", FlashMessageType.Success));
                }
                else
                {
                    SetFlash(new FlashMessage(result.Errors.First(), FlashMessageType.Danger));
                }
            }
            else
                SetFlash(new FlashMessage("Ошибка при заполнении формы", FlashMessageType.Danger));
            return RedirectToAction("Details", "Establishment", new { id = foodEditModel.EstablishmentId });
        }
    }
}

FoodDelivery/Controllers/OrderController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FoodDelivery.Core.Models;
using FoodDelivery.Helpers;
using FoodDelivery.ViewModels.Order;
using AutoMapper;
using FoodDelivery.Domain.Services;
using FoodDelivery.Domain.Dtos.Order;
using FoodDelivery.Domain;
using Microsoft.AspNetCore.Authorization;
using FoodDelivery.ViewModels.FlashMessage;
using FoodDelivery.ViewModels.Food;
using System.Collections.Generic;

namespace FoodDelivery.Controllers
{
    public class OrderController : ControllerBase
    {
        private readonly IOrderService _orderService;
        private readonly IFoodService _foodService;
        private readonly IMapper _mapper;

        public OrderController(IOrderService orderService, IFoodService foodService, IMapper mapper)
        {
            _orderService = orderService;
            _foodService = foodService;
            _mapper = mapper;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var result = _orderService.GetAll();
            var orders = _mapper.Map<IEnumerable<OrderViewModel>>(result.Entity);
            return View(orders);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _orderService.GetByIdAsync(id);
            var order = _mapper.Map<OrderViewModel>(result.Entity);
            return View(order);
        }

        [Authorize(Roles = "Client")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int establishmentId)
        {
            if(ModelState.IsValid)
            {
                var orderViewModel = SessionHelper.GetObjectFromJson<OrderCreateModel>(HttpContext.Session, $"basket{establishmentId}");
                if (orderViewModel == null)
                    ModelState.AddModelError(string.Empty,"Отсутствует информация о заказе");
                var order = _mapper.Map<OrderCreateDto>(orderViewModel);
                order.UserName = User.Identity.Name;
                OperationDetails<Order> operationDetails = await _orderService.CreateAsync(order);
                if (operationDetails.IsSuccess)
                {
                    SessionHelper.RemoveFromSession(HttpContext.Session, $"basket{establishmentId}");
                    SetFlash(new FlashMessage("Заказ успешно оформлен", FlashMessageType.Success));
                    return RedirectToAction("Details", "Establishment", new { id = orderViewModel.EstablishmentId });
                }
                else
                    AddErrors(operationDetails);                   
            }
            return RedirectToAction("Basket", "Establishment", new { id = establishmentId });
        }
        
        public IActionResult AddToBasket(int id)
        {
            var result = _foodService.GetById(id);
            if (result.IsSuccess)
            {
                var food = result.Entity;
                var foodViewModel = _mapper.Map<FoodViewModel>(food);
                if (SessionHelper.GetObjectFromJson<OrderCreateModel>(HttpContext.Session, $"basket{food.EstablishmentId}") == null)
                {
                    var basket = new OrderCreateModel();
                    basket.EstablishmentId = food.EstablishmentId;
                    basket.OrderItems.Add(new OrderItemCreateModel(foodViewModel, 1));
                    SessionHelper.SetObjectAsJson(HttpContext.Session, $"basket{food.EstablishmentId}", basket);
                }
                else
                {
                    var basket = SessionHelper.GetObjectFromJson<OrderCreateModel>(HttpContext.Session, $"basket{food.EstablishmentId}");
                    int index = isExistInBasket(id);
                    if (index != -1)
                    {
                        basket.OrderItems[index].Quantity++;
                    }
                    else
                    {
                        basket.OrderItems.Add(new OrderItemCreateModel(foodViewModel, 1));
                    }
                    SessionHelper.SetObjectAsJson(HttpContext.Session, $"basket{food.EstablishmentId}", basket);
                }
                return RedirectToAction("Details", "Establishment", new { id = food.EstablishmentId });
            }
            else
                return NotFound();
        }

        public IActionResult RemoveFromBasket(int id)
        {
            var result = _foodService.GetById(id);
            if (result.IsSuccess)
            {
                var food = result.Entity;
                var basket = SessionHelper.GetObjectFromJson<OrderCreateModel>(HttpContext.Session, "basket" + food.EstablishmentId);
                var index = isExistInBasket(id);
                basket.OrderItems.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "basket" + food.EstablishmentId, basket);
                if (basket.OrderItems.Count > 0)
                    return RedirectToAction("Basket", "Establishment", new { id = food.EstablishmentId });
                else
                    return RedirectToAction("Details", "Establishment", new { id = food.EstablishmentId });
            }
            return NotFound();
        }

        private int isExistInBasket(int id)
        {
            var result = _foodService.GetById(id);
            if (result.IsSuccess)
            {
                var food = result.Entity;
                var basket = SessionHelper.GetObjectFromJson<OrderCreateModel>(HttpContext.Session, "basket" + food.EstablishmentId);
                for (int i = 0; i < basket.OrderItems.Count; i++)
                {
                    if (basket.OrderItems[i].Food.Id.Equals(id))
                    {
                        return i;
                    }
                }
                return -1;
            }
            else
                throw new Exception();
        }
    }
}

FoodDelivery/Views/Food/_Create.cshtml
@model FoodDelivery.ViewModels.Food.FoodViewModel

<h5>Добавить блюдо</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @Html.HiddenFor(model => model.EstablishmentId)
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" id="addFoodPost"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.EstablishmentId">Отмена</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodDelivery/Views/Food/_Edit.cshtml
@model FoodDelivery.ViewModels.Food.FoodEditModel

<h5>Изменить блюдо</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.EstablishmentId)
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.EstablishmentId">Отмена</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodDelivery/Views/Food/_Index.cshtml
@model IEnumerable<FoodDelivery.ViewModels.Food.FoodViewModel>
@{
    var clientRole = FoodDelivery.Core.Models.RoleEnum.Client.ToString();
    var adminRole = FoodDelivery.Core.Models.RoleEnum.Admin.ToString();
}

<table class="table">
    
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Price)
            </th>
            <th></th>
        </tr>
    
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @Html.HiddenFor(modelItem=>item.Id)
            <td style="vertical-align:middle;">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style="vertical-align:middle;">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td style="vertical-align:middle;">
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            @if (User.IsInRole(clientRole) || !User.Identity.IsAuthenticated)
            {
                <td style="vertical-align:middle;">
                    <a asp-action="AddToBasket" asp-controller="Order" asp-route-id="@item.Id" class="btn btn-info">Заказать</a>
                </td>
            }
            @if (User.IsInRole(adminRole))
            {
                <td style="vertical-align:middle;">
                    <a id="editFood" name="@item.Id"><i class="fas fa-edit text-info"></i></a>
                </td>
            }
        </tr>
        }
    </tbody>
</table>